### PR TITLE
Compat with ebean v12.1.1+

### PR DESCRIPTION
**Pull request by jjlauer**
Ebean has made tremendous progress on current versions.  This makes this module compat with latest versions of Ebean version 12.1.1+

### CODE REVIEW

**Comment by raphaelbauer** [comment]
Travis seems to fail though..

**Comment by jjlauer** [comment]
Fixed travis ci.  Looks like OpenJDK 8 did the trick.

**Comment by jjlauer** [comment]
When you release this, do you mind doing that as v3.0.0 ?

**Comment by raphaelbauer** [comment]
Sure! Will do asap

**Comment by raphaelbauer** [comment]
Released as 3.0.0. 👍

**Pull request merged**
